debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.karma.projectBoard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: karma
    password: 1221
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

#---
#
#spring:
#  datasource:
#    url:
#      jdbc:h2:mem:board:mode=mysql
#    driverClassName:
#      org.h2.Driver
#  config.active.on-profile:
#    testdb
#  sql.init.mode:
#    always
#  test.database.replace:
#    none